name: MAKE PAGE🚀

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Git
        run: |
          git config --global user.name "Sabiya Abraham"
          git config --global user.email "sabiyaabraham10@gmail.com"

      - name: Install Dependencies
        run: |
          cd medonma
          npm install -f

      - name: Build React App
        run: |
          cd medonma
          npm run build
        
      - name: Copy Index.html and Create 404.html
        run: |
          cd medonma/build
          cp index.html 404.html

      - name: Deploy GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          TOKEN: ${{ secrets.TOKEN_PRIVATE }}
          BRANCH: gh-pages
          FOLDER: ./medonma/build